In [8]:
#To find out if a matrice is diagonalizable; the first thing to do is to check wether this matrix is a square matrices meaning matrix of n*n and in python we are doing that by using this condition: if matrix.shape[0] != matrix.shape[1] if it return false that means the matrix is not a square matrix; otherwise it is a square matrix, and then when the matrix respects this condition,
#we have to find the eigen values but determining the characteristic polynim by substracting X to the value situated in the diagonal and then computing the determinant of this new matrix obtaint by substraction the X to the value situated in the diagonal; but in python there are libraries numpy and scipy which handle that, so after computing the determinant of this new matrix, we solve the linear equation obtaining by computing the determinant meaning det(M-IX)=0
#After that we have to find eighen vectors based on the eigen values we found from the eqaution mentionned above, and there are also the same previous libraries are used to do so; but to do so we take each eighen value and then, we found the kernel of the MX-valiX; vali standing for each eigen value.
#Then after doing that based on the vectors found, we can easly check weither the matrix M is diagonalizable; meaning if the number of eigen vectors is equal to the dimension of the matrix, we conclude that the matrix is diaginalizable if the number of eigen vectors is less than the dimansion of the matix , we conclude that the matrix is not diagonalizable.
#Now in case the 

In [8]:
import numpy as np
import pandas as pd
#import seaborn as sns
import scipy.linalg as la

def is_diagonalizable(matrix):
    # Check if matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        print("Error: Matrix is not square")
        return False
    
    # Find eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
    # Check if there are enough linearly independent eigenvectors
    if np.linalg.matrix_rank(eigenvectors) < matrix.shape[0]:
        print("Matrix is not diagonalizable")
        return False
    
    # Create diagonal matrix
    diagonal_matrix = np.zeros(matrix.shape)
    for i in range(matrix.shape[0]):
        diagonal_matrix[i, i] = eigenvalues[i]
    
    # Calculate inverse of eigenvector matrix
    eigenvector_inverse = np.linalg.inv(eigenvectors)
    
    # Calculate diagonalized matrix
    diagonalized_matrix = eigenvectors @ diagonal_matrix @ eigenvector_inverse
    
    # Check if the diagonalized matrix is equal to the original matrix
    if np.allclose(diagonalized_matrix, matrix):
        print("Matrix is diagonalizable")
        print("Diagonal matrix:")
        print(diagonal_matrix)
        return diagonal_matrix
    else:
        print("Matrix is not diagonalizable")
        return False


In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
is_diagonalizable(matrix)


Matrix is diagonalizable
Diagonal matrix:
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]


array([[ 1.61168440e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11684397e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.30367773e-15]])

In [ ]:
Matrix is not diagonalizable
False


In [5]:
matrix = np.array([[1, 2], [2, 1]])
is_diagonalizable(matrix)


Matrix is diagonalizable
Diagonal matrix:
[[ 3.  0.]
 [ 0. -1.]]


array([[ 3.,  0.],
       [ 0., -1.]])

In [6]:
Matrix is diagonalizable
Diagonal matrix:
[[ 3. -0.]
 [-0. -1.]]
array([[ 3., -0.],
       [-0., -1.]])


SyntaxError: invalid syntax (2104626803.py, line 2)

In [10]:
M = np.array([[5, 6, 9, 67, 98],[11, 62, 12, 67, 8], [3, 10, 1, 0, 22], [2, 3, 6, 7, 24], [19, 18, 9, 27, 1]])

In [12]:
is_diagonalizable(M)

Matrix is not diagonalizable


/var/folders/tl/vc1g_x553r9bfykwgkp22fr40000gn/T/ipykernel_95548/1531022610.py:20: ComplexWarning: Casting complex values to real discards the imaginary part
  diagonal_matrix[i, i] = eigenvalues[i]


False

In [13]:
M = np.array([[5, 6, 9, 67, 98],[1, 62, 12, 7, 8], [3, 10, 14, 22, 82], [2, 3, 6, 7, 67], [19, 18, 9, 27, 100]])

In [14]:
is_diagonalizable(M)

Matrix is not diagonalizable


/var/folders/tl/vc1g_x553r9bfykwgkp22fr40000gn/T/ipykernel_95548/1531022610.py:20: ComplexWarning: Casting complex values to real discards the imaginary part
  diagonal_matrix[i, i] = eigenvalues[i]


False

In [15]:
ma = np.array([[1, 2, 1, 4], [2, 0, 1, 3], [-1, 1, 0, 0], [0, 1, -1, 0]])
is_diagonalizable(ma)

Matrix is diagonalizable
Diagonal matrix:
[[ 3.44948974e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.44948974e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.32257656e-15]]


array([[ 3.44948974e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -1.44948974e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.32257656e-15]])